const { APS_CLIENT_ID, APS_CLIENT_SECRET, APS_BUCKET, SERVER_SESSION_SECRET, APS_CALLBACK_URL, VERCEL_BRANCH_URL } =
  process.env;
const INTERNAL_TOKEN_SCOPES = ['data:read'];
const PUBLIC_TOKEN_SCOPES = ['viewables:read'];

if (!APS_CLIENT_ID || !APS_CLIENT_SECRET || !APS_CALLBACK_URL || !INTERNAL_TOKEN_SCOPES || !PUBLIC_TOKEN_SCOPES) {
  process.exit(1);
}

const bucketName = APS_BUCKET || `${APS_CLIENT_ID.toLowerCase()}-basic-app`;

export const API = {
  APS_CLIENT_ID,
  APS_CLIENT_SECRET,
  APS_BUCKET: bucketName,
  APS_CALLBACK_URL,
  SERVER_SESSION_SECRET,
  INTERNAL_TOKEN_SCOPES,
  PUBLIC_TOKEN_SCOPES,
  VERCEL_BRANCH_URL,
};
